version: '3'
services:
  app:
    container_name: plate-reader
    image: plate-reader
    restart: always
    environment:
      - LOG_DIR=/app/logs
      - CONFIG_PATH=/app/config.ini
      - MODEL_WEIGHTS_DIR=/app/model_weights
    volumes:
      - ./logs:/app/logs
      - ./config.ini:/app/config.ini
    ports:
      - 8080:8080
